"""empty message

Revision ID: 5826f59647a9
Revises: c1f5ebce5966
Create Date: 2018-03-19 22:59:45.186453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5826f59647a9'
down_revision = 'c1f5ebce5966'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('biography', sa.String(length=255), nullable=True))
    op.add_column('user_profile', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('user_profile', sa.Column('gender', sa.String(length=20), nullable=True))
    op.add_column('user_profile', sa.Column('location', sa.String(length=255), nullable=True))
    op.drop_constraint(u'user_profile_username_key', 'user_profile', type_='unique')
    op.drop_column('user_profile', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('username', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.create_unique_constraint(u'user_profile_username_key', 'user_profile', ['username'])
    op.drop_column('user_profile', 'location')
    op.drop_column('user_profile', 'gender')
    op.drop_column('user_profile', 'email')
    op.drop_column('user_profile', 'biography')
    # ### end Alembic commands ###
