"""empty message

Revision ID: 87bebbae5587
Revises: 5826f59647a9
Create Date: 2018-03-19 23:38:29.493422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87bebbae5587'
down_revision = '5826f59647a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('pic', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profile', 'pic')
    # ### end Alembic commands ###
